-- MySQL Script generated by MySQL Workbench
-- mié 27 feb 2019 20:25:40 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accounts` (
  `id` INT NOT NULL,
  `avaiable_balance` DECIMAL(10,0) NULL,
  `total_balance` DECIMAL(10,0) NULL,
  `creation_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password_digest` VARCHAR(45) NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`, `account_id`),
  INDEX `fk_users_accounts_idx` (`account_id` ASC),
  CONSTRAINT `fk_users_accounts`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transactions` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `amount` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`goals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`goals` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `goal` VARCHAR(45) NULL,
  `balance` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `deadline` VARCHAR(45) NULL,
  `creation_date` VARCHAR(45) NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_goals_accounts1_idx` (`account_id` ASC),
  CONSTRAINT `fk_goals_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pockets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pockets` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `balance` VARCHAR(45) NULL,
  `pocketscol` VARCHAR(45) NULL,
  `creation_date` VARCHAR(45) NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pockets_accounts1_idx` (`account_id` ASC),
  CONSTRAINT `fk_pockets_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mattresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mattresses` (
  `id` INT NOT NULL,
  `balance` DECIMAL(10,0) NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`, `account_id`),
  INDEX `fk_mattresses_accounts1_idx` (`account_id` ASC),
  CONSTRAINT `fk_mattresses_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`individual_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`individual_transactions` (
  `id` INT NOT NULL,
  `product` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `transaction_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`, `transaction_id`, `account_id`),
  INDEX `fk_individual_transactions_transactions1_idx` (`transaction_id` ASC),
  INDEX `fk_individual_transactions_accounts1_idx` (`account_id` ASC),
  CONSTRAINT `fk_individual_transactions_transactions1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `mydb`.`transactions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_individual_transactions_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mutual_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mutual_transactions` (
  `id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `origin_account_id` INT NOT NULL,
  `final_account_id` INT NOT NULL,
  PRIMARY KEY (`id`, `transaction_id`, `origin_account_id`, `final_account_id`),
  INDEX `fk_mutual_transactions_transactions1_idx` (`transaction_id` ASC),
  INDEX `fk_mutual_transactions_accounts1_idx` (`origin_account_id` ASC),
  INDEX `fk_mutual_transactions_accounts2_idx` (`final_account_id` ASC),
  CONSTRAINT `fk_mutual_transactions_transactions1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `mydb`.`transactions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mutual_transactions_accounts1`
    FOREIGN KEY (`origin_account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mutual_transactions_accounts2`
    FOREIGN KEY (`final_account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
